-- MySQL Script generated by MySQL Workbench
-- 04/14/14 22:33:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seetools
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `seetools` ;
CREATE SCHEMA IF NOT EXISTS `seetools` DEFAULT CHARACTER SET latin1 ;
USE `seetools` ;

-- -----------------------------------------------------
-- Table `seetools`.`email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seetools`.`email` ;

CREATE TABLE IF NOT EXISTS `seetools`.`email` (
  `EmailID` INT NOT NULL AUTO_INCREMENT,
  `EmailAddress` VARCHAR(45) NULL,
  `CreatedByUserID` VARCHAR(45) NOT NULL,
  `CreatedDate` TIMESTAMP NOT NULL,
  `ModifiedByUserID` VARCHAR(45) NOT NULL,
  `ModifiedDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`EmailID`))
ENGINE = InnoDB;

ALTER TABLE `seetools`.`email` AUTO_INCREMENT=1000;
-- -----------------------------------------------------
-- Table `seetools`.`account_activation_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seetools`.`account_activation_token` ;

CREATE TABLE IF NOT EXISTS `seetools`.`account_activation_token` (
  `ActivationTokenID` INT NOT NULL AUTO_INCREMENT,
  `EmailID` INT NOT NULL,
  `Activation_Token` VARCHAR(100) NULL,
  `Active` CHAR NULL,
  `CreatedByUserID` VARCHAR(45) NOT NULL,
  `CreatedDate` TIMESTAMP NOT NULL,
  `ModifiedByUserID` VARCHAR(45) NOT NULL,
  `ModifiedDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ActivationTokenID`))
ENGINE = InnoDB;

ALTER TABLE `seetools`.`account_activation_token` AUTO_INCREMENT=1000;
-- -----------------------------------------------------
-- Table `seetools`.`membership_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seetools`.`membership_types` ;

CREATE TABLE IF NOT EXISTS `seetools`.`membership_types` (
  `MembershipTypeID` INT NOT NULL AUTO_INCREMENT,
  `MembershipType` VARCHAR(45) NULL,
  PRIMARY KEY (`MembershipTypeID`))
ENGINE = InnoDB;

ALTER TABLE `seetools`.`membership_types` AUTO_INCREMENT=1000;
-- -----------------------------------------------------
-- Table `seetools`.`membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seetools`.`membership` ;

CREATE TABLE IF NOT EXISTS `seetools`.`membership` (
  `MembershipID` INT NOT NULL AUTO_INCREMENT,
  `MembershipStatus` VARCHAR(1) NOT NULL DEFAULT 'D',
  `StartDate` TIMESTAMP NULL,
  `ExpiryDate` TIMESTAMP NULL,
  `PaymentAmount` INT NULL,
  `PaymentDate` TIMESTAMP NULL,
  `PaymentMethod` VARCHAR(45) NULL,
  `MembershipTypeID` INT NULL,
  `CreatedByUserID` VARCHAR(45) NULL,
  `CreatedDate` TIMESTAMP NULL,
  `ModifiedByUserID` VARCHAR(45) NULL,
  `ModifiedDate` TIMESTAMP NULL,
  PRIMARY KEY (`MembershipID`),
  INDEX `membership_type_fk_idx` (`MembershipTypeID` ASC),
  CONSTRAINT `membership_type_fk`
    FOREIGN KEY (`MembershipTypeID`)
    REFERENCES `seetools`.`membership_types` (`MembershipTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `seetools`.`membership` AUTO_INCREMENT=10000;

-- -----------------------------------------------------
-- Table `seetools`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seetools`.`user` ;

CREATE TABLE IF NOT EXISTS `seetools`.`user` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `EmailID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `MobileNumber` VARCHAR(15) NULL,
  `Password` VARCHAR(20) NULL,
  `MembershipID` INT NULL,
  `Enabled` CHAR NULL,
  `CreatedByUserID` VARCHAR(45) NOT NULL,
  `CreatedDate` TIMESTAMP NOT NULL,
  `ModifiedByUserID` VARCHAR(45) NOT NULL,
  `ModifiedDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`UserID`),
  INDEX `emailid_fk_idx` (`EmailID` ASC),
  INDEX `membershipid_fk_idx` (`MembershipID` ASC),
  CONSTRAINT `emailid_fk`
    FOREIGN KEY (`EmailID`)
    REFERENCES `seetools`.`email` (`EmailID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `membershipid_fk`
    FOREIGN KEY (`MembershipID`)
    REFERENCES `seetools`.`membership` (`MembershipID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `seetools`.`user` AUTO_INCREMENT=10000;
-- -----------------------------------------------------
-- Table `seetools`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seetools`.`role` ;

CREATE TABLE IF NOT EXISTS `seetools`.`role` (
  `RoleID` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(45) NULL,
  `CreatedByUserID` VARCHAR(45) NOT NULL,
  `CreatedDate` TIMESTAMP NOT NULL,
  `ModifiedByUserID` VARCHAR(45) NOT NULL,
  `ModifiedDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`RoleID`))
ENGINE = InnoDB;

ALTER TABLE `seetools`.`role` AUTO_INCREMENT=100;
-- -----------------------------------------------------
-- Table `seetools`.`failed_login_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seetools`.`failed_login_attempts` ;

CREATE TABLE IF NOT EXISTS `seetools`.`failed_login_attempts` (
  `FailedLoginAttemptID`INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NULL,
  `NumberOfAttempts` INT NULL DEFAULT 0,
  `CreatedByUserID` VARCHAR(45) NULL,
  `CreatedDate` TIMESTAMP NULL,
  `ModifiedByUserID` VARCHAR(45) NULL,
  `ModifiedDate` TIMESTAMP NULL,
  PRIMARY KEY (`FailedLoginAttemptID`),
  INDEX `userid_fk_idx` (`UserID` ASC),
  CONSTRAINT `userid_fk`
    FOREIGN KEY (`UserID`)
    REFERENCES `seetools`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `seetools`.`failed_login_attempts` AUTO_INCREMENT=100;
-- -----------------------------------------------------
-- Table `seetools`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seetools`.`user_role` ;

CREATE TABLE IF NOT EXISTS `seetools`.`user_role` (
  `UserRoleID` INT NOT NULL AUTO_INCREMENT,
  `UserName` INT NOT NULL,
  `RoleID` INT NULL,
  PRIMARY KEY (`UserRoleID`),
  INDEX `UserID_idx` (`UserName` ASC),
  INDEX `RoleID_idx` (`RoleID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserName`)
    REFERENCES `seetools`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RoleID`
    FOREIGN KEY (`RoleID`)
    REFERENCES `seetools`.`role` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE `seetools`.`user_role` AUTO_INCREMENT=100;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
